#! /usr/bin/env bash

# Starts the newstime.love server process.

# To use:
#
#     > script/start

# Ensure pid folders exist
mkdir -p tmp/pids
mkdir -p tmp/sockets

bundle exec unicorn -c config/unicorn.rb -D
